[package]
name = "xlite"
version = "0.2.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
calamine = "0.19.1"
nom = "7.1.3"

[dev-dependencies]
rusqlite = { version = "0.34.0", features = ["bundled", "load_extension"] }
